# Generated by Django 2.2 on 2020-05-08 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menu_group', '0002_menuitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.CharField(default=uuid.uuid1, max_length=255),
        ),
    ]
