# Generated by Django 2.2.5 on 2019-11-12 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=2000)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_group.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'WebSite Page',
            },
        ),
    ]
