# Generated by Django 2.2.5 on 2019-11-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corepage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='corepage',
            name='content',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
