# Generated by Django 2.2.5 on 2019-11-12 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_group', '0001_initial'),
        ('core', '0002_auto_20191112_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corepage',
            options={'verbose_name_plural': 'WebPage'},
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('_data', models.TextField(blank=True, db_column='data')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_group.MenuItem')),
            ],
            options={
                'verbose_name_plural': 'History',
            },
        ),
    ]
