# Generated by Django 2.2.5 on 2019-11-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_group', '0001_initial'),
        ('core', '0003_auto_20191112_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='Admission',
        ),
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name_plural': 'Admission'},
        ),
    ]
