# Generated by Django 2.2.5 on 2019-11-12 19:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191112_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='form_file',
            field=models.FileField(blank=True, upload_to=core.models.get_file_path),
        ),
    ]
