# Generated by Django 2.2.5 on 2019-11-12 19:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admission_form_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('media_file', models.FileField(blank=True, upload_to=core.models.get_file_path)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CorePage')),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
