# Generated by Django 2.2.5 on 2019-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='content',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
