# Generated by Django 2.2.5 on 2019-11-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191122_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corepage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
