# Generated by Django 2.2.7 on 2019-11-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_group', '0002_menuitem_link'),
        ('core', '0008_auto_20191122_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='content',
        ),
        migrations.RemoveField(
            model_name='media',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='media',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
        migrations.AddField(
            model_name='media',
            name='core_page_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu_group.MenuItem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
