# Generated by Django 2.2.7 on 2019-12-12 17:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_media_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_file', models.ImageField(blank=True, upload_to=core.models.get_file_path)),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
