# Generated by Django 2.2.7 on 2019-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
