# Generated by Django 2.2.7 on 2019-12-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
