# Generated by Django 2.2.7 on 2019-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_event_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
