# Generated by Django 2.2 on 2020-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191216_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='content',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
