# Generated by Django 2.2.5 on 2019-11-17 15:54

from django.db import migrations, models
import django.db.models.deletion
import faculty.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('profile_image', models.FileField(upload_to=faculty.models.get_file_path)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
            ],
            options={
                'verbose_name_plural': 'Faculty Profile',
            },
        ),
    ]
