# Generated by Django 2.2.7 on 2019-11-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20191124_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
