# Generated by Django 2.2.7 on 2019-11-24 10:34

from django.db import migrations, models
import faculty.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_auto_20191124_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=faculty.models.get_file_path),
        ),
    ]
