# Generated by Django 2.2.7 on 2019-11-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_auto_20191124_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
